filenames:
    - /var/log/traefik/access.log
labels:
    type: traefik

---
source: appsec
name: myAppSecComponent
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/virtual-patching
labels:
    type: appsec

---
filenames:
    - /var/log/auth.log
labels:
    type: syslog
