# REVERSE PROXY

volumes:
    server_traefik_letsencrypt:
    server_traefik_logs:
        external: true
    server_crowdsec_config:
        external: true
    server_crowdsec_data:
        external: true

networks:
    traefik_proxy:
        external: true
    docker_socket_proxy:
        external: true

services:
    # ----------------------------------------
    # TRAEFIK
    # Reverse Proxy + SSL Support
    # ----------------------------------------
    traefik:
        image: traefik:v3.6
        container_name: traefik
        user: root
        environment:
            DOMAIN: ${DOMAIN}
            CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
        networks:
            - traefik_proxy
            - docker_socket_proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - server_traefik_letsencrypt:/letsencrypt
            - server_traefik_logs:/var/log/traefik
        command:
            - --api.dashboard=true
            ## -- observability
            - --log.level=debug
            - --accessLog.filePath=/var/log/traefik/access.log
            - --accesslog=true
            - --accessLog.format=common
            - --accesslog.fields.defaultmode=keep
            - --accesslog.fields.headers.defaultmode=keep
            - --accesslog.fields.headers.names.Authorization=drop
            ## -- providers
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.endpoint=tcp://socket-proxy:2375
            ## -- entrypoints
            - --entryPoints.web.address=:80
            - --entryPoints.web.forwardedHeaders.trustedIPs=${TRUSTED_IPS} # (optional) forward headers on trusted IPs
            - --entryPoints.websecure.address=:443
            - --entryPoints.websecure.forwardedHeaders.trustedIPs=${TRUSTED_IPS} # (optional) forward headers on trusted IPs
            ## -- tls certificates
            - --certificatesresolvers.myresolver.acme.email=${CERTS_EMAIL}
            - --certificatesresolvers.myresolver.acme.storage=letsencrypt/acme.json
            - --certificatesresolvers.myresolver.acme.dnschallenge=true
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
            ## -- plugins
            - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
            - "--experimental.plugins.bouncer.version=v1.5.1"
        labels:
            traefik.enable: true
            traefik.docker.network: traefik_proxy

            ## -- Router dashboard
            traefik.http.routers.traefik-dashboard.service: api@internal
            traefik.http.routers.traefik-dashboard.rule: Host(`traefik.${DOMAIN}`)
            traefik.http.routers.traefik-dashboard.entrypoints: websecure
            traefik.http.routers.traefik-dashboard.tls.certresolver: myresolver
            traefik.http.routers.traefik-dashboard.middlewares: crowdsec, authentik-auth

            ## -- Middelware "ratelimit"
            # traefik.http.middlewares.ratelimit.ratelimit.average: 100
            # traefik.http.middlewares.ratelimit.ratelimit.period: 1m

            ## -- Middelware "authentik-auth"
            traefik.http.middlewares.authentik-auth.forwardAuth.address: http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
            traefik.http.middlewares.authentik-auth.forwardAuth.trustForwardHeader: true
            traefik.http.middlewares.authentik-auth.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

            ## -- Middelware "crowdsec-bouncer-traefik-plugin"
            traefik.http.middlewares.crowdsec.plugin.bouncer.enabled: true
            traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode: stream
            traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclhost: crowdsec:8080
            traefik.http.middlewares.crowdsec.plugin.bouncer.forwardedheaderstrustedips: ${TRUSTED_IPS}
            traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey: ${CROWDSEC_TRAEFIK_API_KEY}
            traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled: true
            traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsechost: crowdsec:7422

            # -- Watchtower
            com.centurylinklabs.watchtower.enable: "true"
        restart: always
        depends_on:
            - crowdsec

    # ----------------------------------------
    # CROWDSEC
    # Security Engine + Traefik Bouncer
    # ----------------------------------------
    crowdsec:
        image: crowdsecurity/crowdsec
        container_name: crowdsec
        user: root
        environment:
            COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/sshd "
            CUSTOM_HOSTNAME: crowdsec
            BOUNCER_KEY_TRAEFIK: ${CROWDSEC_TRAEFIK_API_KEY}
            APPSEC_URL: 0.0.0.0:7422
        networks:
            - traefik_proxy
        ports:
            - 8080:8080
            - 7422:7422
        volumes:
            - ./crowdsec/acquis.yml:/etc/crowdsec/acquis.yaml:ro
            - /var/log/auth.log:/var/log/auth.log:ro
            - server_traefik_logs:/var/log/traefik:ro
            - server_crowdsec_config:/etc/crowdsec/
            - server_crowdsec_data:/var/lib/crowdsec/data/
        labels:
            traefik.enable: false
            com.centurylinklabs.watchtower.enable: "true"
            docker-volume-backup.stop-during-backup: crowdsec
        restart: unless-stopped
