# VPN client

volumes:
    server_vpn_gluetun_data:

networks:
    traefik_proxy:
        external: true

services:
    # ----------------------------------------
    # GLUETUN
    # Vpn client
    # ----------------------------------------
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        user: root
        cap_add:
            - NET_ADMIN
        environment:
            TZ: ${TZ}
            VPN_SERVICE_PROVIDER: ${VPN_PROVIDER}
            OPENVPN_USER: ${VPN_USER}
            OPENVPN_PASSWORD: ${VPN_PASSWORD}
            SERVER_REGIONS: ${VPN_REGIONS}
            DNS_SERVER: on
            DNS_UPSTREAM_RESOLVERS: cloudflare
            VPN_PORT_FORWARDING: on
            HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: /gluetun/auth/config.toml
        entrypoint: >
            sh -c "mkdir -p /gluetun/auth &&
            echo '[[roles]]' > /gluetun/auth/config.toml &&
            echo 'name = \"sync-mod\"' >> /gluetun/auth/config.toml &&
            echo 'routes = [\"GET /v1/portforward\"]' >> /gluetun/auth/config.toml &&
            echo 'auth = \"apikey\"' >> /gluetun/auth/config.toml &&
            echo 'apikey = \"${GSP_GTN_API_KEY}\"' >> /gluetun/auth/config.toml &&
            exec /gluetun-entrypoint"
        networks:
            - traefik_proxy
        ports:
            - ${QBITTORRENT_PORT}:8888
            - ${NZBGET_PORT}:6789
        volumes:
            - server_vpn_gluetun_data:/gluetun
        devices:
            - /dev/net/tun:/dev/net/tun
        labels:
            traefik.enable: true
            traefik.docker.network: traefik_proxy
            # -- qbittorrent
            traefik.http.routers.qbittorrent.service: qbittorrent
            traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.${DOMAIN}`)
            traefik.http.routers.qbittorrent.entrypoints: websecure
            traefik.http.routers.qbittorrent.tls.certresolver: myresolver
            traefik.http.services.qbittorrent.loadbalancer.server.port: 8888
            traefik.http.routers.qbittorrent.middlewares: authentik-auth
            # -- nzbget
            # traefik.http.routers.nzbget.service: nzbget
            # traefik.http.routers.nzbget.rule: Host(`nzbget.${DOMAIN}`)
            # traefik.http.routers.nzbget.entrypoints: websecure
            # traefik.http.routers.nzbget.tls.certresolver: myresolver
            # traefik.http.services.nzbget.loadbalancer.server.port: 6789
            # traefik.http.routers.nzbget.middlewares: authentik-auth
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
