# STREAMING MEDIA MANAGEMENT

# volumes:
#     riven_postgresql_data:
#     riven_postgresql_dumps:
#         external: true
#     riven_legacy_postgresql_data:
#     riven_legacy_postgresql_dumps:
#         external: true

networks:
    traefik_proxy:
        external: true
    prowlarr:
    # riven:

services:
    # ----------------------------------------
    # JELLYFIN
    # An alternative to Plex
    # ----------------------------------------
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        tty: true
        environment:
            TZ: ${TZ}
            PUID: ${PUID}
            PGID: ${PGID}
            JELLYFIN_PublishedServerUrl: https://jellyfin.${DOMAIN}
        networks:
            - traefik_proxy
        ports:
            - ${JELLYFIN_PORT}:8096
            - 7359:7359/udp
            - 1900:1900/udp
        volumes:
            - /srv/docker/jellyfin/config:/config
            - ${MEDIA_UNIFIED_PATH}/tvshows:/data/tvshows
            - ${MEDIA_UNIFIED_PATH}/movies:/data/movies
            # - ${MEDIA_UNIFIED_PATH}/riven:/mount:rslave,z
        labels:
            # -- traefik
            traefik.enable: true
            traefik.http.routers.jellyfin.rule: Host(`jellyfin.${DOMAIN}`)
            traefik.http.routers.jellyfin.entrypoints: websecure
            traefik.http.routers.jellyfin.tls.certresolver: myresolver
            traefik.http.services.jellyfin.loadbalancer.server.port: 8096
            # traefik.http.routers.jellyfin.middlewares: authentik-auth // forward auth is disabled for now to prefer a LDAP settings in jellyfin and allow mobile app access
            # -- backup
            docker-volume-backup.stop-during-backup: jellyfin-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        restart: unless-stopped

    # ----------------------------------------
    # SEER
    # A media discovery and recommendation engine that integrates with Jellyfin, Sonarr, Radarr
    # ----------------------------------------
    seerr:
        image: ghcr.io/seerr-team/seerr:latest
        container_name: seerr
        user: ${PUID}:${PGID}
        tty: true
        init: true
        environment:
            TZ: ${TZ}
            LOG_LEVEL: info
        networks:
            - traefik_proxy
        ports:
            - ${SEER_PORT}:5055
        volumes:
            - /srv/docker/seerr/config:/app/config
        labels:
            # -- traefik
            traefik.enable: true
            traefik.http.routers.seerr.rule: Host(`seerr.${DOMAIN}`)
            traefik.http.routers.seerr.entrypoints: websecure
            traefik.http.routers.seerr.tls.certresolver: myresolver
            # -- backup
            docker-volume-backup.stop-during-backup: seerr-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
            start_period: 20s
            timeout: 3s
            interval: 15s
            retries: 3
        restart: unless-stopped

    # ----------------------------------------
    # PROWLARR
    # Index management
    #
    # FLARESOLVER
    # a proxy server to bypass Cloudflare and DDoS-GUARD protection
    #
    # BYPARR
    # a proxy server to bypass ByPass-GUARD protection
    # ----------------------------------------
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        tty: true
        environment:
            TZ: ${TZ}
            PUID: ${PUID}
            PGID: ${PGID}
        networks:
            - traefik_proxy
            - prowlarr
        ports:
            - ${PROWLARR_PORT}:9696
        volumes:
            - /srv/docker/prowlarr/config:/config
        labels:
            # -- traefik
            traefik.enable: true
            traefik.docker.network: traefik_proxy
            traefik.http.routers.prowlarr.rule: Host(`prowlarr.${DOMAIN}`)
            traefik.http.routers.prowlarr.entrypoints: websecure
            traefik.http.routers.prowlarr.tls.certresolver: myresolver
            traefik.http.routers.prowlarr.middlewares: authentik-auth
            # -- backup
            docker-volume-backup.stop-during-backup: prowlarr-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        restart: unless-stopped

    flaresolverr:
        image: flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        user: root
        environment:
            LOG_LEVEL: info
            TZ: ${TZ}
            LANG: en_GB
            CAPTCHA_SOLVER: none
            HEADLESS: true
        networks:
            - prowlarr
        ports:
            - ${PROWLARR_FLARESOLVER_PORT}:8191
        restart: unless-stopped

    byparr:
        image: ghcr.io/thephaseless/byparr:latest
        container_name: byparr
        networks:
            - prowlarr
        ports:
            - ${PROWLARR_BYPARR_PORT}:8191
        labels:
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        shm_size: 2gb
        restart: unless-stopped

    # ----------------------------------------
    # SONARR
    # TV Series Management
    # ----------------------------------------
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        tty: true
        environment:
            TZ: ${TZ}
            PUID: ${PUID}
            PGID: ${PGID}
        networks:
            - traefik_proxy
        ports:
            - ${SONARR_PORT}:8989
        volumes:
            - /srv/docker/sonarr/config:/config
            - ${MEDIA_PATH}:/downloads
            - ${MEDIA_UNIFIED_PATH}/tvshows:/tv
        labels:
            # -- traefik
            traefik.enable: true
            traefik.docker.network: traefik_proxy
            traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`)
            traefik.http.routers.sonarr.entrypoints: websecure
            traefik.http.routers.sonarr.tls.certresolver: myresolver
            traefik.http.routers.sonarr.middlewares: authentik-auth
            # -- backup
            docker-volume-backup.stop-during-backup: sonarr-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        restart: unless-stopped

    # ----------------------------------------
    # RADARR
    # Movies Management
    # ----------------------------------------
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        tty: true
        environment:
            TZ: ${TZ}
            PUID: ${PUID}
            PGID: ${PGID}
        networks:
            - traefik_proxy
        ports:
            - ${RADARR_PORT}:7878
        volumes:
            - /srv/docker/radarr/config:/config
            - ${MEDIA_PATH}:/downloads
            - ${MEDIA_UNIFIED_PATH}/movies:/movies
        labels:
            # -- traefik
            traefik.enable: true
            traefik.docker.network: traefik_proxy
            traefik.http.routers.radarr.rule: Host(`radarr.${DOMAIN}`)
            traefik.http.routers.radarr.entrypoints: websecure
            traefik.http.routers.radarr.tls.certresolver: myresolver
            traefik.http.routers.radarr.middlewares: authentik-auth
            # -- backup
            docker-volume-backup.stop-during-backup: radarr-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
            com.centurylinklabs.watchtower.monitor-only: "true"
        restart: unless-stopped

    # ----------------------------------------
    # RIVEN
    # Torrent streaming through Debrid
    # ----------------------------------------
    # riven-frontend:
    #     image: riven-frontend-local:latest # local build for testing and development
    #     # image: spoked/riven-frontend:dev
    #     container_name: riven-frontend
    #     user: ${PUID}:${PGID}
    #     tty: true
    #     environment:
    #         RIVEN_LOG_LEVEL: DEBUG
    #         TZ: ${TZ}
    #         DATABASE_URL: /riven/data/riven.db
    #         BACKEND_URL: http://riven:8080
    #         BACKEND_API_KEY: ${RIVEN_BACKEND_API_KEY}
    #         AUTH_SECRET: ${RIVEN_AUTH_SECRET}
    #         ORIGIN: https://riven.${DOMAIN}
    #     networks:
    #         - traefik_proxy
    #         - riven
    #     ports:
    #         - ${RIVEN_FRONTEND_PORT}:3000
    #     volumes:
    #         - /srv/docker/riven/frontend/data:/riven/data
    #     labels:
    #         # -- traefik
    #         traefik.enable: true
    #         traefik.docker.network: traefik_proxy
    #         traefik.http.routers.riven-frontend.rule: Host(`riven.${DOMAIN}`)
    #         traefik.http.routers.riven-frontend.entrypoints: websecure
    #         traefik.http.routers.riven-frontend.tls.certresolver: myresolver
    #         traefik.http.routers.riven-frontend.middlewares: authentik-auth
    #         # -- backup
    #         docker-volume-backup.stop-during-backup: riven-frontend-service
    #     restart: unless-stopped
    #     depends_on:
    #         riven:
    #             condition: service_started

    # riven:
    #     image: riven-local:test # local build for testing and development
    #     # image: spoked/riven:dev
    #     container_name: riven
    #     tty: true
    #     privileged: true
    #     cap_add:
    #         - SYS_ADMIN
    #     devices:
    #         - /dev/fuse
    #     security_opt:
    #         - apparmor:unconfined
    #     shm_size: 1024m
    #     environment:
    #         RIVEN_LOG_LEVEL: DEBUG
    #         PUID: ${PUID}
    #         PGID: ${PGID}
    #         TZ: ${TZ}
    #         # database
    #         # RIVEN_FORCE_ENV: true
    #         RIVEN_DATABASE_HOST: postgresql+psycopg2://${RIVEN_POSTGRES_USER}:${RIVEN_POSTGRES_PASSWORD}@riven-postgresql/${RIVEN_POSTGRES_DB}
    #         # VFS Configuration
    #         RIVEN_UPDATERS_LIBRARY_PATH: /mount
    #         RIVEN_FILESYSTEM_MOUNT_PATH: /mount
    #         RIVEN_FILESYSTEM_CACHE_DIR: /dev/shm/riven-cache
    #         RIVEN_FILESYSTEM_CACHE_MAX_SIZE_MB: 10240
    #         RIVEN_FILESYSTEM_CACHE_EVICTION: TTL
    #         RIVEN_FILESYSTEM_CACHE_TTL_SECONDS: 3600
    #         RIVEN_FILESYSTEM_CHUNK_SIZE_MB: 16
    #         RIVEN_FILESYSTEM_FETCH_AHEAD_CHUNKS: 4
    #     networks:
    #         - traefik_proxy
    #         - riven
    #         - prowlarr
    #     ports:
    #         - ${RIVEN_BACKEND_PORT}:8080
    #     volumes:
    #         - /srv/docker/riven/backend/data:/riven/data
    #         - ${MEDIA_UNIFIED_PATH}/riven:/mount:rshared,z
    #     labels:
    #         traefik.enable: true
    #         traefik.docker.network: traefik_proxy
    #         traefik.http.routers.riven-backend.rule: Host(`riven-api.${DOMAIN}`)
    #         traefik.http.routers.riven-backend.entrypoints: websecure
    #         traefik.http.routers.riven-backend.tls.certresolver: myresolver
    #         traefik.http.services.riven-backend.loadbalancer.server.port: 8080
    #         # -- backup
    #         docker-volume-backup.stop-during-backup: riven-service
    #     healthcheck:
    #         test: curl -s http://localhost:8080 >/dev/null || exit 1
    #         interval: 30s
    #         timeout: 10s
    #         retries: 10
    #     restart: unless-stopped
    #     depends_on:
    #         riven-postgresql:
    #             condition: service_healthy

    # riven-postgresql:
    #     image: postgres:17-alpine
    #     container_name: riven-postgresql
    #     user: root
    #     environment:
    #         POSTGRES_USER: ${RIVEN_POSTGRES_USER}
    #         POSTGRES_PASSWORD: ${RIVEN_POSTGRES_PASSWORD}
    #         POSTGRES_DB: ${RIVEN_POSTGRES_DB}
    #         # path config
    #         PGDATA: /var/lib/postgresql/data/pgdata
    #     networks:
    #         - riven
    #     volumes:
    #         - riven_postgresql_data:/var/lib/postgresql/data/pgdata
    #         - riven_postgresql_dumps:/tmp/dumps
    #         - ../backups/scripts/postgres-backup.sh:/postgres-backup.sh:ro
    #     labels:
    #         docker-volume-backup.exec-label: riven-postgresql
    #         docker-volume-backup.archive-pre: sh -c '/postgres-backup.sh'
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U postgres"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #     restart: unless-stopped

    # riven-frontend-legacy:
    #     image: spoked/riven-frontend:latest
    #     container_name: riven-frontend-legacy
    #     user: ${PUID}:${PGID}
    #     tty: true
    #     environment:
    #         TZ: ${TZ}
    #     networks:
    #         - traefik_proxy
    #         - riven
    #     ports:
    #         - ${RIVEN_FRONTEND_PORT}:3000
    #     volumes:
    #         - /srv/docker/riven-legacy/frontend/config:/riven/config
    #     labels:
    #         # -- traefik
    #         traefik.enable: true
    #         traefik.docker.network: traefik_proxy
    #         traefik.http.routers.riven-frontend-legacy.rule: Host(`riven.${DOMAIN}`)
    #         traefik.http.routers.riven-frontend-legacy.entrypoints: websecure
    #         traefik.http.routers.riven-frontend-legacy.tls.certresolver: myresolver
    #         traefik.http.routers.riven-frontend-legacy.middlewares: authentik-auth
    #         # -- backup
    #         docker-volume-backup.stop-during-backup: riven-legacy-frontend-service
    #     restart: unless-stopped
    #     depends_on:
    #         riven-legacy:
    #             condition: service_started

    # riven-legacy:
    #     image: spoked/riven:main
    #     container_name: riven-legacy
    #     tty: true
    #     cap_add:
    #         - SYS_ADMIN
    #     devices:
    #         - /dev/fuse
    #     security_opt:
    #         - apparmor:unconfined
    #     shm_size: 1024m
    #     environment:
    #         PUID: ${PUID}
    #         PGID: ${PGID}
    #         TZ: ${TZ}
    #         RIVEN_FORCE_ENV: true
    #         RIVEN_DATABASE_HOST: postgresql+psycopg2://${RIVEN_POSTGRES_USER}:${RIVEN_POSTGRES_PASSWORD}@riven-legacy-postgresql/${RIVEN_POSTGRES_DB}
    #     networks:
    #         - traefik_proxy
    #         - riven
    #         - prowlarr
    #     ports:
    #         - ${RIVEN_BACKEND_PORT}:8080
    #     volumes:
    #         - /srv/docker/riven-legacy/backend/data:/riven/data
    #         - ${MEDIA_UNIFIED_PATH}/riven:/mnt:rshared,z
    #     labels:
    #         traefik.enable: true
    #         traefik.docker.network: traefik_proxy
    #         traefik.http.routers.riven-backend-legacy.rule: Host(`riven-api.${DOMAIN}`)
    #         traefik.http.routers.riven-backend-legacy.entrypoints: websecure
    #         traefik.http.routers.riven-backend-legacy.tls.certresolver: myresolver
    #         traefik.http.services.riven-backend-legacy.loadbalancer.server.port: 8080
    #         # -- backup
    #         docker-volume-backup.stop-during-backup: riven-legacy-service
    #     healthcheck:
    #         test: curl -s http://localhost:8080 >/dev/null || exit 1
    #         interval: 30s
    #         timeout: 10s
    #         retries: 10
    #     restart: unless-stopped
    #     depends_on:
    #         riven-legacy-postgresql:
    #             condition: service_healthy

    # riven-legacy-postgresql:
    #     image: postgres:17-alpine
    #     container_name: riven-legacy-postgresql
    #     user: root
    #     environment:
    #         POSTGRES_USER: ${RIVEN_POSTGRES_USER}
    #         POSTGRES_PASSWORD: ${RIVEN_POSTGRES_PASSWORD}
    #         POSTGRES_DB: ${RIVEN_POSTGRES_DB}
    #         # path config
    #         PGDATA: /var/lib/postgresql/data/pgdata
    #     networks:
    #         - riven
    #     volumes:
    #         - riven_legacy_postgresql_data:/var/lib/postgresql/data/pgdata
    #         - riven_legacy_postgresql_dumps:/tmp/dumps
    #         - ../backups/scripts/postgres-backup.sh:/postgres-backup.sh:ro
    #     labels:
    #         docker-volume-backup.exec-label: riven-legacy-postgresql
    #         docker-volume-backup.archive-pre: sh -c '/postgres-backup.sh'
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U postgres"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #     restart: unless-stopped
