# BACKUP

volumes:
    authentik_postgresql_dumps:
        external: true
    server_crowdsec_config:
        external: true
    server_crowdsec_data:
        external: true

networks:
    docker_socket_proxy:
        external: true
    traefik_proxy:
        external: true

services:
    # ----------------------------------------
    # DOCKER VOLUME BACKUP
    # Backup Docker volumes locally or to compatible storage
    # documentation: https://offen.github.io/docker-volume-backup/
    # ----------------------------------------
    docker-volume-backup:
        image: offen/docker-volume-backup:latest
        container_name: docker-volume-backup
        user: root
        environment:
            NOTIFICATION_LEVEL: info
            GPG_PASSPHRASE: ${GPG_PASSPHRASE}
            DOCKER_HOST: tcp://socket-proxy:${SOCKET_PROXY_PORT}
            # NOTIFICATION_URLS: ${BACKUP_BACKUP_NOTIFICATION_URLS}
        networks:
            - docker_socket_proxy
        volumes:
            # -- backup config
            - ./backup-volume-docker:/etc/dockervolumebackup/conf.d

            # -- services volumes to backup (sources)
            # auth
            - authentik_postgresql_dumps:/backup/authentik-postgresql-dump:ro
            - /srv/docker/authentik/data:/backup/authentik-server-data:ro
            - /srv/docker/authentik/templates:/backup/authentik-server-templates:ro
            - /srv/docker/authentik/certs:/backup/authentik-server-certs:ro
            # backup
            - /srv/docker/rclone/config:/backup/rclone-config:ro
            # cloud
            - /srv/docker/filebrowser-quantum/data:/backup/filebrowser-quantum-data:ro
            # devtools
            - /srv/docker/opencode/config/:/backup/opencode-config:ro
            - /srv/docker/opencode/data/:/backup/opencode-data:ro
            - /srv/docker/obsidian-livesync/etc:/backup/obsidian-livesync-etc:ro
            - /srv/docker/obsidian-livesync/data:/backup/obsidian-livesync-data:ro
            # domotic
            - /srv/docker/home-assistant/data:/backup/home-assistant-data:ro
            # downloads
            - /srv/docker/qbittorrent/config/:/backup/qbittorrent-config:ro
            # monitoring
            - /srv/docker/uptime-kuma/data/:/backup/uptime-kuma-data:ro
            # reverse proxy
            - server_crowdsec_config:/backup/crowdsec-config:ro
            - server_crowdsec_data:/backup/crowdsec-data:ro
            # streaming
            - /srv/docker/jellyfin/config:/backup/jellyfin-config:ro
            - /srv/docker/seerr/config:/backup/seerr-config:ro
            - /srv/docker/prowlarr/config:/backup/prowlarr-config:ro
            - /srv/docker/sonarr/config:/backup/sonarr-config:ro
            - /srv/docker/radarr/config:/backup/radarr-config:ro

            # -- path to local backup (destination)
            - ${LOCAL_BACKUPS_PATH}/docker-volume-backup:/archive
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    # ----------------------------------------
    # RCLONE
    # Rclone server for remote management of backups and other files
    # ----------------------------------------
    rclone:
        image: rclone/rclone:latest
        container_name: rclone
        user: ${PUID}:${PGID}
        networks:
            - traefik_proxy
        ports:
            - ${RCLONE_PORT}:5572
        volumes:
            - /srv/docker/rclone/config:/config/rclone
            # -- sources
            - /mnt/das-cloud/documents:/src/das-cloud/documents:ro
            - /mnt/das-cloud/immich:/src/das-cloud/immich:ro
            # -- destinations
            - /mnt/das-cloud/backups:/dest/das-cloud/backups
        command: >
            rcd --rc-web-gui --rc-addr :5572
            --rc-user ${RCLONE_USER}
            --rc-pass ${RCLONE_PASS}
            --cache-dir /config/rclone/cache
        labels:
            # -- traefik
            traefik.enable: true
            traefik.docker.network: traefik_proxy
            traefik.http.routers.rclone.rule: Host(`rclone.${DOMAIN}`)
            traefik.http.routers.rclone.entrypoints: websecure
            traefik.http.routers.rclone.tls.certresolver: myresolver
            traefik.http.routers.rclone.middlewares: crowdsec, authentik-auth
            traefik.http.services.rclone.loadbalancer.server.port: 5572
            # -- backup
            docker-volume-backup.stop-during-backup: rclone-service
            # -- version monitoring
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
